#+TITLE: ragev - RAG Evaluation Report

* Overview
Conducted a RAG system evaluation with these parameters changed:
- document splitters; size-based, context-based
- embedding models; all-minilm, nomic, qwen3 0.6b
- LLM models; llama3.1:8b, gemini-2.5-flash-lite
- Re-ranking enabled/disabled

Tech Stack: Python, Emacs/Org-mode, ChromaDB, Ollama (Llama 3.1, Qwen3), Gemini 2.5 Flash and ms-marco-MiniLM-L6-v2

#+begin_src mermaid
graph LR
    %% User and Core App
    User((User)) --- ragev[ragev App]

    %% Local Knowledge Engine
    subgraph Local_Stack [Local Knowledge]
        direction TB
        DB[(ChromaDB)] --- AI_L[Local AI: Qwen/Llama]
    end

    %% Cloud Brain
    subgraph Cloud_Eval [Cloud Quality Control]
        Gemini[Gemini Flash-Lite]
    end

    %% Minimal Connections
    ragev <--> Local_Stack
    ragev <--> Cloud_Eval
#+end_src


** Motivation
RAG systems are sensitive to multiple interacting components (chunking, embeddings, retrieval, re-ranking).  This project evaluates how these components affect retrieval quality and answer correctness in a controlled setup.

The goal is to identify practical configurations that improve:
- retrieval accuracy (Recall@K, MRR)
- answer quality (faithfulness, correctness)

while highlighting tradeoffs and failure modes.

** Key takeaways
*** Embedding
- size=600 & overlap=60 was the sweet spot
- Context-based splitter with sub-splitting large sections was better than context-based only or size/overlap only
- Embedding model matters.  qwen3-embedding was the winner.

*** Queries
- LLMs are useful to generate queries with keywords and reference answers
- You need to manually check and update as they may have hallucinations

*** Evaluation
- Prompt matters for better LLM evaluation with faithfulness and correctness.  Introducing CoT (Chain-of-Thought) reduced hallucinations
- Still, you need to look at logs to see if LLM evaluation was correct

*** LLM usage
- To stabilize results, setting temperature (& seed) is important
- I saw false positives and negatives.  LLMs are not reliable.  Reducing hallucinations is a challenge.
- Transforming queries to sequences of keywords worsen the results for the dataset.  Hypothesis:
  - Original queries were already aligned with source documents
  - Removing 'noises' also removed context
- Re-ranking improved overall metrics.  But the improvement to MRR was significant (0.82 \to 1.00) because it directly pushed the most relevant chunk to the top.


* Quick start
- Install Python
  - pyenv and venv recommended
  - tested with 3.14.0 but should work with 3.11 or later
#+begin_src 
pyenv install 3.14.0
pyenv global 3.14.0
cd ragev
python -m venv ve
source ve/bin/activate
#+end_src
- Install ollama and models
#+begin_src 
curl -fsSL https://ollama.com/install.sh | sh
ollama pull all-minilm:latest
ollama pull nomic-embed-text
ollama pull llama3.1:8b
ollama pull qwen3-embedding:0.6b
ollama list # to verify
#+end_src
- pip install
#+begin_src 
pip install -U chromadb
pip install -U ollama
pip install -U google-genai
pip install -U sentence-transformers
#+end_src
- git clone ragev repo
#+begin_src 
git clone git@github.com:achiwa912/ragev.git
#+end_src
- prepare data files and other directories
#+begin_src 
mkdir chroma
mkdir results
mkdir data
cd data
mkdir org
cd org
wget https://github.com/achiwa912/vbs/blob/main/README.org
mv README.org vbs.org
#+end_src
- I also used the blog entries from the source .org file
  - https://blog.achiwa.co.uk/posts/homelab_minipc/ -> homelab.org
  - https://blog.achiwa.co.uk/posts/advprompt/ -> advanced.org
- Embed
#+begin_src 
python ingest.py
-> stops at breakpoint() and run:
ingest(size=600, overlap=60, embed_str='qwen3-embedding:0.6b', context_based=True)
#+end_src
- Run an eval round
#+begin_src 
python eval.py
-> stops at breakpoint() and run:
eval(col_name='qwe_s600_o60_context', top_k=6, model_ans='gemini-2.5-flash-lite', model_eval='gemini-2.5-flash-lite', model_embed='qwen3-embedding:0.6b', model_rerank='cross-encoder/ms-marco-MiniLM-L6-v2', retrieve_only=False, qtrans=False, rerank=True)
#+end_src

* Test environment

#+begin_src mermaid
graph TD
    User((User)) -->|Query| App[ragev App]
    subgraph Local Context
        App -->|Embed| Qwen[Qwen3-Embedding]
        Qwen -->|Search| DB[(ChromaDB)]
        DB -->|Context| Rerank{Re-ranker}
    end
    subgraph Cloud Eval
        Rerank -->|Top-K| Gemini[Gemini-2.5-Flash-Lite]
    end
    Gemini -->|Answer| User
#+end_src

** Hardware
*** AceMagic V1
- Intel N150, 16GB RAM, 1TB SSD
- Ubuntu 24.04.2 LTS (12GB RAM assigned) on Proxmox 8.4.0
  - GPU not available

*** Laptop (Mac/Chromebook)
- Editing Python scripts and documents
- Quick local tests

** Vector DB and embedding/LLM models
*** Vector DB for embedding
- ChromaDB 1.5.7
- Collection name format: <embed_model>__s<size>_o<overlap>_<splitter>
  - embed_model: all: all-minilm:latest, nom: nomic-embed-text:latest, qwe: qwen3-embedding:0.6b
  - size: chunk size in number of characters
  - overlap: overlap in number of characters
  - splitter: sizeonly or context

*** LLM models
**** Ollama
#+begin_src 
(ve) ~/py/ragev % ollama list
NAME                       ID              SIZE      MODIFIED     
qwen3-embedding:0.6b       ac6da0dfba84    639 MB    25 hours ago    
llama3.1:8b                46e0c10c039e    4.9 GB    6 days ago      
nomic-embed-text:latest    0a109f422b47    274 MB    13 days ago     
llama3.2:3b                a80c4f17acd5    2.0 GB    3 weeks ago     
all-minilm:latest          1b226e2802db    45 MB     3 weeks ago     
#+end_src

**** Gemini API
- gemini-2.5-flash-lite

*** Cross-encoder
- cross-encoder/ms-marco-MiniLM-L6-v2

** Files and directories
*** Files
- cli_chroma.py - show collection list, etc. for ChromaDB
- config.py - config parameters
- eval.py - eval() runs a test round (eg, 20 queries)
- ingest.py - ingest() embed data files (3 .org files) to ChromaDB
- keywords_checker.py - check if all keywords are in the data files (debug)
- questions.py, questions.orig - 20 queries
- retrieve.py 
  - retrieve() retrieves similar chunks to user query
  - answer() LLM generates answer based on retrieved chunks and the query

*** Directories
- chroma/ - chroma database files
- results/ - test logs in jsonl
  - eval_YYYYMMDD_HHMMSS.jsonl eg, eval_20260401_195903.jsonl
- data/org/ - data files

** Dataset
- 3 documents (~5 KB total)
- Domain: personal github project README and technical blog content (flashcard app, prompting, homelab)
- Total chunks after splitting: 120
| document     | chunks |
|--------------+--------|
| vbs.org      |     29 |
| homelab.org  |     34 |
| advanced.org |     57 |
|--------------+--------|
| total        |    120 |

* Methodologies
Each experiment varies a single parameter while keeping others fixed:
- One variable changed per experiment
- 20 fixed queries used across all runs
- Results averaged over one run (future work: multiple seeds)
- Base config: size=600, overlap=60, top_k=6, qwen3 embedding

** Parameters
- Chunk splitters
  - Size-based
    - Size: specify chunk size in number in characters
    - Overlap: how many characters are overlapped between 2 continuous chunks
  - Context-based: split by .org headers (ie, startswith('*'))
  - Context-based + sub-split large sections
- top_k: how many chunks similar to a query are retrieved
- embedding model: all-minilm, nomic-embed-text or qwen3-embedding:0.6b
- answer model:  gemini-2.5-flash-lite or llama3.1:8b
- eval model: gemini-2.5-flash-lite or llama3.1:8b
- query transformation: ask LLM to transform the query to be more vector DB friendly (ie, remove noise and add keywords that LLM knows)

** Queries
- Asked Claude to generate 20 queries.  Prompt used:
#+begin_src 
For my RAG eval, write 20 questions.  Include 3 questions that require combining information from multiple sentences.  For each questions, pick up three key words and generate an expected answer.  Generate your answer based only on the document below, not from your general knowledge.  Give me your answer in a python dicstionaries in a list so that I can copy and paste like this: [{"id": "q01", "query": "What is PREV?", "keywords": ["aaa", "bbb ccc", "ddd"], "expected_answer": "Plan, .."}, ...]
The doc:
#+end_src
- Checked and updated manually
  - "expected_answer" -> "reference_answer"
  - changed some keywords (eg, not appear in data files)
  - asked Claude to re-generate 3 incorrect queries

Samples:
#+begin_src python
questions_keywords = [
    {
        "id": "q01",
        "query": "What does PREV stand for and what is its purpose?",
        "keywords": ["Plan", "Verify", "self-criticism"],
        "reference_answer": "PREV stands for Plan, Reason, Execute and Verify. Its purpose is to address the LLM weakness of jumping into conclusions too early by forcing the LLM to slow down and verify its output."
    },
    {
        "id": "q02",
        "query": "What does ReAct stand for and what loop does it use?",
        "keywords": ["Reason-Action", "Thought", "Observation"],
        "reference_answer": "ReAct stands for Reason-Action. It is a micro-pattern that breaks a step into a Thought, Action, Observation loop."
    },
# <snip>
#+end_src


** Metrics
I wrote four scorers, two to see retrieval quality and two for end-to-end quality.
*** Retrieval
- Recall@K - percentage of keywords appear in top_k chunks
  - Recall@K is approximated using keyword matching rather than labeled relevant chunks.
  - This introduces noise but avoids manual annotation.
- MRR (Mean Reciprocal Rank) - how early in (top_k) chunks any keyword appear

*** End-to-end
- Faithfulness - ask LLM to rate if answer is generated solely from top_k chunks
- Answer correctness - ask LLM if the answer answers query

** Limitations
- Single run per configuration (no variance estimation)
- Small dataset (20 queries)
- Results may not generalize


* Results and findings
*** Chunk size (number of characters)
- Overlap is 1/10 of chunk size
- Top_k=5, embed_model=all-minilm:latest
- Note: I saw ingest errors for (chunk) size=1000, likely due to limited context size for the minilm model.

#+begin_src mermaid :file images/size.png
xychart-beta
    title "RAG Eval: Recall@k vs MRR"
    x-axis "Size" [100, 200, 400, 600, 800, 1000]
    y-axis "Score" 0 --> 1
    line [0.35, 0.60, 0.77, 0.83, 0.88, 0.85]
    line [0.47, 0.57, 0.79, 0.89, 0.86, 0.75]
#+end_src

| size     |  100 |  200 |  400 |  600 |  800 | 1000 |
| overlap  |   10 |   20 |   40 |   60 |   80 |  100 |
|----------+------+------+------+------+------+------|
| recall@k | 0.35 | 0.60 | 0.77 | 0.83 | 0.88 | 0.85 |
| MRR      | 0.47 | 0.57 | 0.79 | 0.89 | 0.86 | 0.75 |
- (chunk) size=800, overlap=80 is the winner, close second is size=600, overlap=60
- small chunks can't contain enough context
- a large chunk may have multiple sections/paragraphs

*** Overlap
- Size=600 characters, top_k=5, embed_model=all-minilm:latest
- Note: as I see ingest errors with size=800, overlap>=40, I tested with size=600
#+begin_src mermaid :file images/overlap.png
xychart-beta
  title "RAG Eval: Recall@k vs MRR (size=600)"
  x-axis "Overlap" [0, 20, 50, 60, 80, 100]
  y-axis "Score" 0 --> 1
  line [0.83, 0.70, 0.77, 0.83, 0.78, 0.73]
  line [0.82, 0.77, 0.74, 0.89, 0.85, 0.77]
#+end_src

| size     |  600 |  600 |  600 |  600 |  600 |  600 |
| overlap  |    0 |   20 |   50 |   60 |   80 |  100 |
|----------+------+------+------+------+------+------|
| recall@k | 0.83 | 0.70 | 0.77 | 0.83 | 0.78 | 0.73 |
| MRR      | 0.82 | 0.77 | 0.74 | 0.89 | 0.85 | 0.77 |
- Size=600, overlap=60 (overlap is 10% of size) is the winner
- too small overlap (less than 10%) is worse than no overlap
- too large overlap could effectively reduce total amount of information in top_k chunks

*** top_k
- Size=600, overlap=60, embed_model=all-minilm:latest
#+begin_src mermaid :file images/topk.png
xychart-beta
  title "RAG Eval: Recall@k vs MRR (size=600, overlap=60)"
  x-axis "top_k" [3, 4, 5, 6, 7, 8]
  y-axis "Score" 0 --> 1
  line [0.83, 0.83, 0.87, 0.90, 0.90, 0.90]
  line [0.89, 0.89, 0.89, 0.89, 0.89, 0.89]
#+end_src
| top_k    |    3 |    4 |    5 |    6 |    7 |    8 |
|----------+------+------+------+------+------+------|
| recall@k | 0.83 | 0.83 | 0.87 | 0.90 | 0.90 | 0.90 |
| MRR      | 0.89 | 0.89 | 0.89 | 0.89 | 0.89 | 0.89 |
- top_k>=6 maxed out.
- changing top_k doesn't affect MRR as expected

*** LLM models for answer
- Note: using gemini for LLM for eval, hoping for better judgment.
#+begin_src mermaid :file images/llmmodels.png
xychart-beta
  title "RAG Eval: llama3.1:8b vs gemini-2.5-flash-lite"
  x-axis ["Recall@k", "MRR", "Faithfulness", "Correctness"]
  y-axis "Score (0.0 - 1.0)" 0 --> 1
  line [0.90, 0.89, 0.94, 0.72]
  line [0.90, 0.89, 0.98, 0.79]
#+end_src#+end_src
| answer model          | recall@k |  MRR | Faithfulness | Correctness |
|-----------------------+----------+------+--------------+-------------|
| llama3.1:8b           |     0.90 | 0.89 |         0.94 |        0.72 |
| gemini-2.5-flash-lite |     0.90 | 0.89 |         0.98 |        0.79 |
- Gemini is the winner simply because it's a much larger LLM \to stronger reasoning though Google doesn't disclose the exact parameter count (8B vs. estimated 20B+)
- An important note is that your data is exposed to Google Gemini if you use it for answers.  Using Gemini as an evaluation LLM for an eval project shouldn't matter.

*** Embed models
#+begin_src mermaid :file images/embedmodels.png
xychart-beta
  title "RAG Eval: all-minilm vs nomic vs qwen3"
  x-axis ["Recall@k", "MRR", "Faithfulness", "Correctness"]
  y-axis "Score (0.0 - 1.0)" 0 --> 1
  line [0.90, 0.89, 0.98, 0.79]
  line [0.63, 0.66,  0.64, 0.49]
  line [0.92, 0.87, 0.94, 0.82]
#+end_src#+end_src
| embed model             | recall@k |  MRR | Faithfulness | Correctness |
|-------------------------+----------+------+--------------+-------------|
| all-minilm:latest       |     0.90 | 0.89 |         0.98 |        0.79 |
| nomic-embed-text:latest |     0.63 | 0.66 |         0.64 |        0.49 |
| qwen3-embedding:0.6b    |     0.92 | 0.87 |         0.94 |        0.82 |
- Tie all-minilm:latest vs qwen3-embedding:0.6b
- nomic underperformed significantly.  Hypothesis:
  - The dataset is small and domain specific
  - nomic is optimized for larger, more diverse corpora
  - all-minilm and qwen3 might better capture short-context semantics

*** Splitter - context-based + sub-split
| embed model             | recall@k |  MRR | Faithfulness | Correctness |
|-------------------------+----------+------+--------------+-------------|
| all-minilm:latest       |     0.92 | 0.84 |         0.94 |        0.83 |
| nomic-embed-text:latest |     0.73 | 0.61 |         0.76 |        0.61 |
| qwen3-embedding:0.6b    |     0.95 | 0.82 |         0.98 |        0.85 |

Comparing size- vs context-based for qwen3
#+begin_src mermaid :file images/splitters.png
xychart-beta
  title "RAG Eval: size-based vs context-based"
  x-axis ["Recall@k", "MRR", "Faithfulness", "Correctness"]
  y-axis "Score (0.0 - 1.0)" 0 --> 1
  line [0.92, 0.87, 0.94, 0.82]
  line [0.95, 0.82, 0.98, 0.85]
#+end_src#+end_src
| splitter      | recall@k |  MRR | Faithfulness | Correctness |
|---------------+----------+------+--------------+-------------|
| size-based    |     0.92 | 0.87 |         0.94 |        0.82 |
| context-based |     0.95 | 0.82 |         0.98 |        0.85 |
- Overall winner is qwen3-embedding & context-based + sub-split
- MRR dropped.  This means that keywords were not in an earlier chunk in a section.  But, as recall@k is high, it shouldn't matter much.

*** Query transformation
#+begin_src mermaid :file images/qtrans.png
xychart-beta
  title "RAG Eval: query transformation"
  x-axis ["Recall@k", "MRR", "Faithfulness", "Correctness"]
  y-axis "Score (0.0 - 1.0)" 0 --> 1
  line [0.95, 0.82, 0.98, 0.85]
  line [0.67, 0.64, 0.66, 0.53]
#+end_src#+end_src
| Query Trans | recall@k |  MRR | Faithfulness | Correctness |
|-------------+----------+------+--------------+-------------|
| disabled    |     0.95 | 0.82 |         0.98 |        0.85 |
| enabled     |     0.67 | 0.64 |         0.66 |        0.53 |
- Query transformation worsened the numbers.
- Possibly losing context/exact phrasing by removing 'noises', and/or queries generated by Claude are more in line with original texts

*** Re-ranking
- Used cross-encoder to reorder results from ChromaDB
- Re-ranker: cross-encoder/ms-marco-MiniLM-L6-v2
- context-based+subsplit (size=600, overlap=60), qwen3-embedding:0.6b, gemini-2.5-flash-lite
#+begin_src mermaid :file images/rerank.png
xychart-beta
  title "RAG Eval: re-ranking"
  x-axis ["Recall@k", "MRR", "Faithfulness", "Correctness"]
  y-axis "Score (0.0 - 1.0)" 0 --> 1
  line [0.95, 0.82, 0.98, 0.85]
  line [0.97, 1.00, 1.00, 0.85]
#+end_src#+end_src
| Re-rank  | recall@k |  MRR | Faithfulness | Correctness |
|----------+----------+------+--------------+-------------|
| disabled |     0.95 | 0.82 |         0.98 |        0.85 |
| enabled  |     0.97 | 1.00 |         1.00 |        0.85 |
- Re-ranking worked as expected for recall@k and MRR, especially the latter improved significantly from 0.82 to perfect 1.00 as re-ranking pushed important chunks to top.
- After all, transformer attention of cross-encoder suits more than simple cosine similarities of vector DB in ordering relevant chunks to user queries.

*** Summary
#+begin_src mermaid :file images/summary.png
xychart-beta
  title "RAG Eval: recall@k(blue),MRR(green),Faith(red),Corct(yellow)"
  x-axis ["Base", "+Gemini", "+Qwen3", "+Context", "+rerank"]
  y-axis "Score (0.0 - 1.0)" 0 --> 1
  line [0.90, 0.90, 0.92, 0.95, 0.97]
  line [0.89, 0.89, 0.87, 0.82, 1.00]
  line [0.94, 0.98, 0.94, 0.98, 1.00]
  line [0.72, 0.79, 0.82, 0.85, 0.85]
#+end_src#+end_src
Base: size=600, overlap=60, top_k=6

**** Best-config among tested
- Context-based splitter with sub-splitting large sections (size=600, overlap=60)
- top_k = 6
- Embed-model: qwen3-embedding:0.6b
- LLM-model: gemini-2.5-flash-lite
- No query transformation
- Re-ranking enabled (ms-marco-MiniLM-L6-v2)
